

[TBAVW95]
TbCheckNoAVOk
NoStatusWindow
LastScan = 05/17/2000, 04:35:05
StartupWhenBooting = 1
StartupTarget = 
SmallWindowPosRight = 250
SmallWindowPosBottom = 80
SmallWindowPosLeft = 540
SmallWindowPosTop = 468
WindowPosRight = 550
WindowPosBottom = 400
WindowPosLeft = 125
WindowPosTop = 76
; NoQuitMsg


[TbAvWin]
StartupWhenBooting = 1



