;/*********************************************************************
;
;   Module Name:   install.ini
;
;   Module Code:   TOOLKIT
;
;   Author:              
;
;   Creation Date:       Aug 12, 1991
;
;   Copyright Lotus Development Corporation, (c) 1991
;
;
; *
; * Description: 
; *
;
;   Additional authors:
;
;   Change History:
;   $Log:   V:\logfiles\cominst\orgkit\cinstall.i@i  $
; 
;    Rev 1.2   27 Dec 1994 16:03:58   tveerapp
; 
; Added a new field LAUNCHEXE.
; 
;    Rev 1.1   22 Feb 1994 13:32:58   jbrodeur
;  fix for Node Install 
; 
;    Rev 1.0   11 Feb 1994 10:53:18   jbrodeur
; Initial Revision
;----------------------------------------------------------------------
;   Date     Vers. Pgmr  SPR#  Change
;----------------------------------------------------------------------
;   02-02-94 0000  MMETH       Initial checkin
;!
;
;----------------------------------------------------------------------
;
;*********************************************************************/

[TOOLKIT]
CUIDLL=MSCUISTF.DLL
STDINFFILE=ORG.INF
SRVINFFILE=ORG.INF
NODEINFFILE=ORGNODE.INF
BYWIREINFFILE=ORGDIST.INF
LAUNCHEXE=
