                          þþþþþþþþþþþþþþþþþþþþþþþþþ
                         þþþþþþþþþþþþþþþþþþþþþþþþþþþ
                        þþþþþþþþþþþþþþþþþþþþþþþþþþþþþ
                        -<->-<->-<->-<->-<->-<->-<->-
                               Ebola Virus Crew
                                 Member-Apply
                        -<->-<->-<->-<->-<->-<->-<->-
                        þþþþþþþþþþþþþþþþþþþþþþþþþþþþþ
                         þþþþþþþþþþþþþþþþþþþþþþþþþþþ
                          þþþþþþþþþþþþþþþþþþþþþþþþþ

                           Your special pseudnoym:
                    -[.................................]-



                       As what you want apply by EVC:

        Coder   *Cracker  Graphic Artist  *Hacker  *Virii Specialist
        -[ ]-     -[ ]-       -[ ]-        -[ ]-         -[ ]-

   (The * at the beginning of some jobs indicates, that we want/prefer
    people who has knowledge in working as cracker, hacker, virii spec.
    More info about the jobs are on our homepage! - http://beam.to/Evc)



                           What you can offer EVC?
                        (what specialities you have?)
                     -[...............................]-



                Are you member in a other group? (Which one?)
                            -[.................]-



            You can program? (We hope so! - at least a little)
                Tell us in which language you CAN program:

                 Assembler    Basic      C       Delphi
                   -[ ]-      -[ ]-    -[ ]-      -[ ]-

                 T. Pascal    Visual Basic        Other
                   -[ ]          -[ ]-       -[...........]-

            
           How do you REALLY assess your ability of programming?

        Very good       Good         O.K.      Not bad      Beginner
          -[ ]-         -[ ]-       -[ ]-       -[ ]-        -[ ]-

                      Other notes about your programming:

                      -[...............................]-
                      -[...............................]-
                      -[...............................]-


       In case you've cracked something yet or programmed a cool prog,
        then please send it to us. We check it out and look into it.
 

             How we can reach you? (Internet/Mailbox/Fidonet/etc.)

                     Internet-[........................]
                     Mailbox-<[........................]
                     Fidonet-<[........................]
                     Other-<>-[........................]


 
 Apply-Form '98 by: SuB zErO-[evc_subzero@hotmail.com]
